# Hard iron as float
HARD_IRONX: 33.0
HARD_IRONY: 15.0
HARD_IRONZ: -1.0

# Orientation quaternion as float
# 2.7 pitch
Q0: 0.999722430218001
Q1: 0.0
Q2: 0.0235597648336102
Q3: 0.0

# Differential pressure sensor offset
DPRESS: 92.8817
